"""
Scheduled one-off events/appointments: /addevent, /events, /rescheduleevent,
/removeevent -- flat, dated entries like "Dinner with Mel next Monday" or a
week's worth of workout-plan slots ("Monday: pull day in the gym"), distinct
from tasks.py's to-dos (no due/overdue framing, no "done" state -- an event
just passes by date) and from reminders.py's daily reminders (a single
occurrence, not a habit that recurs every day forever).

Deliberately flat/one-off for now, not truly recurring (e.g. "Company Tennis
every Wednesday") -- a real recurring rule needs day-of-week/interval
matching plus the classic "edit one occurrence vs. all future occurrences"
problem, and this codebase has no established pattern for either yet. The
concrete near-term driver (committing a week's workout plan to the
schedule) is really just several flat dated rows, regenerated by a fresh
planning conversation each week -- not a true recurring rule -- so building
flat events now fully covers it without guessing at recurrence design ahead
of a real driving case. True recurrence can be designed properly later, once
there's a concrete need for it.

ADD (a single event, or a whole list in one message -- e.g. seven workout
slots for the week) and SHOW work directly through the add_event/show_events
intents. Clearing or moving an existing event ALSO works by natural
language, but through correction.py's target_domain="event" path (actions
"delete" and "reschedule" -- see its own module docstring), not through a
dedicated intent here -- "the X-ray is done"/"cancel dinner with Mel" reads
as a delete correction, and "push day should be tomorrow"/"correct that to
the 23rd" reads as a reschedule correction, the same as "delete that
expense" or "that was actually 2 days ago". This needed ai.parse_message to
be handed a recent-upcoming-events list (see its docstring for why that was
a real, deliberate signature change, not the same "avoid widening the call"
cut reminders.py made) -- added after a real observed bug: without it, an
event id had no way to be told apart from a task id, so "X is done" against
an event confidently misfired as a task correction instead.

Natural-language rescheduling (correction_action="reschedule") was added
after a second, more serious real observed bug: before it existed, a
date-correction message ("correct both to 2026-09-23") had no matching
action for events at all (only "delete" was ever supported), and the model
chose "delete" instead of asking for clarification -- silently destroying
two real scheduled events instead of moving them. /rescheduleevent <id>
<days from today> still exists as the direct command-line equivalent (and
is what natural language now calls under the hood, via db.edit_event_date),
but the natural-language path is what most messages actually go through, so
it needed the same capability, not just a "that command exists" pointer.
"""

from datetime import date, timedelta

from telegram import Update
from telegram.ext import ContextTypes

import ai
import db
from access import _reject_if_not_allowed
from correction import LAST_CORRECTION_KEY
from formatting import _event_line
from replies import _reply


def _events_text(chat_id: int) -> str:
    """Shared by /events and the natural-language show_events intent -- see
    finance._balance_text's docstring for why. Upcoming (today forward,
    soonest first) only -- a past event has nothing left to show for, unlike
    a to-do that stays open/overdue until done."""
    rows = db.get_upcoming_events(chat_id)
    if not rows:
        return "Nothing on your schedule right now."
    return "Upcoming:\n" + "\n".join(_event_line(r) for r in rows)


def _event_date_from_days(event_in_days) -> str | None:
    """Deterministic event-date computation in Python -- the model only ever
    extracts a day-count, never a calendar date (same discipline as
    tasks._due_at_from_fields and correction.py's days_ago elsewhere)."""
    if not isinstance(event_in_days, int) or event_in_days < 0:
        return None
    today = date.fromisoformat(db.today_str())
    return (today + timedelta(days=event_in_days)).isoformat()


async def _add_event_and_reply(update: Update, chat_id: int, data: dict):
    """data may come from either parse_message's natural-language schema
    (event_title/event_in_days/event_time/event_notes) or extract_event's
    own field names (title/event_in_days/event_time/notes) -- same merge
    pattern as tasks._log_task_and_reply."""
    title = data.get("event_title") or data.get("title") or "event"
    event_in_days = data.get("event_in_days")
    event_time = data.get("event_time")
    notes = data.get("event_notes") or data.get("notes")
    event_date = _event_date_from_days(event_in_days)
    if event_date is None:
        await _reply(update, chat_id, f"What day is \"{title}\" on?")
        return
    event_id = db.add_event(chat_id, title, event_date, event_time, notes)
    row = db.get_event(chat_id, event_id)
    await _reply(update, chat_id, f"Added to your schedule: {_event_line(row)}")


async def _add_events_and_reply(update: Update, chat_id: int, events: list):
    """Entry point for the natural-language add_event intent, which can name
    several events in one message (e.g. a whole week's workout plan, one
    event per day) -- same multi-item discipline as tasks._log_tasks_and_reply.
    A single event reuses _add_event_and_reply's exact wording unchanged;
    more than one gets ONE combined reply, each event on its own line."""
    if len(events) == 1:
        await _add_event_and_reply(update, chat_id, events[0])
        return

    lines = []
    skipped = 0
    for e in events:
        title = e.get("event_title") or e.get("title") or "event"
        event_date = _event_date_from_days(e.get("event_in_days"))
        event_time = e.get("event_time")
        notes = e.get("event_notes") or e.get("notes")
        if event_date is None:
            skipped += 1
            continue
        event_id = db.add_event(chat_id, title, event_date, event_time, notes)
        row = db.get_event(chat_id, event_id)
        lines.append(_event_line(row))

    if not lines:
        await _reply(update, chat_id, "I couldn't tell what day any of those were on -- try again with dates.")
        return
    header = f"Added {len(lines)} to your schedule:"
    if skipped:
        header += f" ({skipped} skipped -- no day given)"
    body = "\n".join(lines)
    await _reply(update, chat_id, f"{header}\n{body}")


async def addevent_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if await _reject_if_not_allowed(update):
        return
    chat_id = update.effective_chat.id
    description = " ".join(context.args)
    if not description:
        await update.message.reply_text("Usage: /addevent dinner with Mel next Monday")
        return
    data = ai.extract_event(description)
    await _add_event_and_reply(update, chat_id, data)


async def events_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if await _reject_if_not_allowed(update):
        return
    chat_id = update.effective_chat.id
    await update.message.reply_text(_events_text(chat_id))


async def rescheduleevent_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if await _reject_if_not_allowed(update):
        return
    chat_id = update.effective_chat.id
    if len(context.args) < 2:
        await update.message.reply_text(
            "Usage: /rescheduleevent <id> <days from today> -- e.g. /rescheduleevent 3 1 for tomorrow "
            "(see /events for IDs)"
        )
        return
    try:
        event_id = int(context.args[0])
        days_from_today = int(context.args[1])
    except ValueError:
        await update.message.reply_text(
            "Usage: /rescheduleevent <id> <days from today> -- e.g. /rescheduleevent 3 1"
        )
        return
    if days_from_today < 0:
        await update.message.reply_text("Give a day count from today (0 = today, 1 = tomorrow, ...).")
        return
    row = db.get_event(chat_id, event_id)
    if row is None:
        await update.message.reply_text("Couldn't find that event -- run /events to check the ID.")
        return
    old_date = row["event_date"]
    today = date.fromisoformat(db.today_str())
    new_date = (today + timedelta(days=days_from_today)).isoformat()
    updated = db.edit_event_date(chat_id, event_id, new_date)
    context.chat_data[LAST_CORRECTION_KEY] = {
        "domain": "event", "action": "reschedule", "event_id": event_id, "old_date": old_date,
    }
    await update.message.reply_text(
        f"Rescheduled: {_event_line(updated)} (was {old_date}). Reply 'undo' if that's wrong."
    )


async def removeevent_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if await _reject_if_not_allowed(update):
        return
    chat_id = update.effective_chat.id
    if not context.args:
        await update.message.reply_text("Usage: /removeevent <id> (see /events for IDs)")
        return
    try:
        event_id = int(context.args[0])
    except ValueError:
        await update.message.reply_text("That doesn't look like an event ID. Try: /removeevent 3")
        return
    deleted = db.delete_event(chat_id, event_id)
    if deleted is None:
        await update.message.reply_text("Couldn't find that event -- run /events to check the ID.")
        return
    context.chat_data[LAST_CORRECTION_KEY] = {"domain": "event", "action": "delete", "row": deleted}
    await update.message.reply_text(f"Removed: {_event_line(deleted)}. Reply 'undo' if that's wrong.")
